---
# npm path: cPanel often uses nodevenv/AppName/AppName/18/bin (or system ea-nodejs18).
deployment:
  tasks:
    - export PATH="$HOME/nodevenv/devsrus.co.za/devsrus.co.za/18/bin:/opt/cpanel/ea-nodejs18/bin:$PATH" && npm install --production
