---
# cPanel Git deployment: these tasks run after each pull.
# Runs from your application root (the repo directory).
#
# After deployment, restart your Node.js app in cPanel (Setup Node.js App → Restart)
# if it doesn’t auto-restart.

deployment:
  tasks:
    - npm install --production=false
    - npm run build
