---
# Use your Node.js app's npm (app: devsrus.co.za, root: repositories/devsrus, node 18).
deployment:
  tasks:
    - export PATH="$HOME/nodevenv/devsrus.co.za/18/bin:$PATH" && npm install --production
